### ISSUE TITLE
Fix the island code example

### ISSUE THREAD

**Issue by fityannugroho** [fityannugroho/idn-area#205]
## Describe the bug
The `code` example for `GET /islands/{code}` endpoint is wrong.

## To Reproduce
1. Go to `/docs` endpoint
3. Scroll down to `GET /islands/{code}`
3. Click on `GET /islands/{code}` section
4. Click "Try it out" button
5. Click "Execute"
6. See the error

## Expected behavior
The docs gives real island code example, which is `110140001`.

## Screenshots or Error logs
![image](https://github.com/fityannugroho/idn-area/assets/63894003/7d545519-e578-4d13-a326-cfd078e38d74)

## Additional context

**Guide for contributor**
- Take a look at `island.dto.ts` file.
- Find `Island` class and `code` property inside it.
- Change the value of `example` argument in the `@ApiProperty()` decorator into '110140001'.
- That's it.

**Comment by pratikk3008** [comment]
Hey, i can fix this bug.
Can you please assign this to me?
