### ISSUE TITLE
Translate the README to other language

### ISSUE THREAD

**Issue by fityannugroho** [fityannugroho/idn-area#95]
Translate the README into Bahasa Indonesia and other languages.

## Guide

- Save the translation files in `docs` folder and named it with `README_{2 letter of language code}.md` the language code must follows the [ISO 639-1 code languages](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes), e.g. `README_id.md` for Indonesian (Bahasa Indonesia).
- Create new PR and fill the form by following the [contribution guide](https://github.com/fityannugroho/idn-area/blob/main/CONTRIBUTING.md). Make sure you reference this issue (`#95`) in your PR
- Make sure all links is working, especially link in TOC and link to other file in this repo.
  - The links in the table of content (TOC) also need to be translated to make it work. The link is a **snake-case** version of the header **without any symbol**.
  - Use **relative paths** for links that go to other files (see the [following article](https://www.redhat.com/sysadmin/linux-path-absolute-relative)).

> For everyone who wants to contribute to this issue, please fork this repo, make changes, and create a new PR. When ready, ask me to review your work. From now on, I will not assign each person individually.

**Comment by CharithaCS** [comment]
I'd love to contribute to this. I can translate it to hindi. Please assign me this. Thanks!

**Comment by kaustab28** [comment]
I can translate it to Tagalog(filipino). The translation may not be perfect, especially for complex or nuanced sentences. Although I will try my best. 
Could you please assign it to me under Hacktoberfest?

**Comment by fityannugroho** [comment]
Okay, I'll assign you both.

- Hindi `hi` : @CharithaCS 
- Tagalog `tl` : @kaustab28

**Comment by ghost** [comment]
I would love to translate it to Nepalese language. Could you please assign it to me under Hacktoberfest?

**Comment by fityannugroho** [comment]
> I would love to translate it to Nepalese language. Could you please assign it to me under Hacktoberfest?

Okay. I will assign you

**Comment by tedante** [comment]
Hello @fityannugroho , 
I would love to translate it to Indonesia, 
Can you please assign it to me?
Thank you

**Comment by Shashankpantiitbhilai** [comment]
i would love to translate it into chinese or french,please assign it to me

**Comment by fityannugroho** [comment]
> i would love to translate it into chinese or french,please assign it to me

@Shashankpantiitbhilai So do you want to translate into chinese, french, or both?

**Comment by Shashankpantiitbhilai** [comment]
Majorly french

**Comment by fityannugroho** [comment]
> Majorly french

In this case, I'll assign you to translate into French.

**Comment by fityannugroho** [comment]
For everyone who wants to contribute to this issue, please fork this repo, make changes, and create a new PR. When ready, ask me to review your work. From now on, I will not assign each person individually.

**Comment by fityannugroho** [comment]
For everyone who wants to contribute to this issue, please fork this repo, make changes, and create a new PR. When ready, ask me to review your work. From now on, I will not assign each person individually.
